var json = {
    "item1": {
        "name": ["Item Name:", "iPad"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$500.00"],
        "date": ["Pledge Date:", "10/17/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$250.00"],
        "motivation": ["Motivation:", "Buying it for school."],
        "space": ["<br>", "<br>"]
    },
    "item2": {
        "name": ["Item Name:", "iPhone"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$200.00"],
        "date": ["Pledge Date:", "10/18/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$40.00"],
        "motivation": ["Motivation:", "Buying it for school and work."],
        "space": ["<br>", "<br>"]
    },
    "item3": {
        "name": ["Item Name:", "iMac"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$2000.00"],
        "date": ["Pledge Date:", "10/17/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "Between 1-3 years"],
        "amountSaved": ["Amount Saved:", "$100.00"],
        "motivation": ["Motivation:", "Buying it for work and entertainment."],
        "space": ["<br>", "<br>"]
    },
    "item4": {
        "name": ["Item Name:", "Beats by Dre Solo Headphones"],
        "brand": ["Item Brand:", "Beats Electronics"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$200.00"],
        "date": ["Pledge Date:", "10/24/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$20.00"],
        "motivation": ["Motivation:", "Buying it for entertainment."],
        "space": ["<br>", "<br>"]
    },
    "item5": {
        "name": ["Item Name:", "iPhone Case"],
        "brand": ["Item Brand:", "OtterBox"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$50.00"],
        "date": ["Pledge Date:", "10/25/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$15.00"],
        "motivation": ["Motivation:", "Buying it to protect my iPhone 4s."],
        "space": ["<br>", "<br>"]
    },
    "item6": {
        "name": ["Item Name:", "55\" 1080p HDTV "],
        "brand": ["Item Brand:", "Samsung"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$3999.99"],
        "date": ["Pledge Date:", "10/24/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "More than 3 years"],
        "amountSaved": ["Amount Saved:", "$150.00"],
        "motivation": ["Motivation:", "Buying it for my living room."],
        "space": ["<br>", "<br>"]
    },
    "item7": {
        "name": ["Item Name:", "$50 iTunes Cars"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$50.00"],
        "date": ["Pledge Date:", "10/24/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$5.00"],
        "motivation": ["Motivation:", "Buying it to keep from using my debit card so much."],
        "space": ["<br>", "<br>"]
    },
    "item8": {
        "name": ["Item Name:", "Blue Jeans"],
        "brand": ["Item Brand:", "Levi"],
        "quantity": ["Quantity:", "3"],
        "cost": ["Total Cost:", "$150.00"],
        "date": ["Pledge Date:", "10/26/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$35.00"],
        "motivation": ["Motivation:", "Need them for the Winter."],
        "space": ["<br>", "<br>"]
    },
    "item9": {
        "name": ["Item Name:", "Jacket"],
        "brand": ["Item Brand:", "Not Sure"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$60.00"],
        "date": ["Pledge Date:", "10/23/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$22.00"],
        "motivation": ["Motivation:", "Need it for the Winter cold."],
        "space": ["<br>", "<br>"]
    },
    "item10": {
        "name": ["Item Name:", "White Shoes"],
        "brand": ["Item Brand:", "Radii Footwear"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$110.00"],
        "date": ["Pledge Date:", "10/25/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$15.00"],
        "motivation": ["Motivation:", "Want them for the Spring."],
        "space": ["<br>", "<br>"]
    },
    "item11": {
        "name": ["Item Name:", "7\" Android Tablet"],
        "brand": ["Item Brand:", "Samsung"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$250.00"],
        "date": ["Pledge Date:", "10/25/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$18.00"],
        "motivation": ["Motivation:", "Want to down size my tablet from 10.1\" to a 7\" tablet"],
        "space": ["<br>", "<br>"]
    },
    "item12": {
        "name": ["Item Name:", "Thunderbolt Display"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$999.99"],
        "date": ["Pledge Date:", "10/20/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "Between 1-3 years"],
        "amountSaved": ["Amount Saved:", "$10.00"],
        "motivation": ["Motivation:", "Want a bigger display for design purposes."],
        "space": ["<br>", "<br>"]
    },
    "item13": {
        "name": ["Item Name:", "Bed"],
        "brand": ["Item Brand:", "Ashley's Furniture"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$350.00"],
        "date": ["Pledge Date:", "09/12/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$50.00"],
        "motivation": ["Motivation:", "Need a new bed frame and headboard."],
        "space": ["<br>", "<br>"]
    },
    "item14": {
        "name": ["Item Name:", "Printer"],
        "brand": ["Item Brand:", "HP"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$100.00"],
        "date": ["Pledge Date:", "08/04/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$15.00"],
        "motivation": ["Motivation:", "Needed for school and work purposes."],
        "space": ["<br>", "<br>"]
    },
    "item15": {
        "name": ["Item Name:", "Halo 4"],
        "brand": ["Item Brand:", "Bungie"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$60.00"],
        "date": ["Pledge Date:", "10/14/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$22.00"],
        "motivation": ["Motivation:", "Need for entertainment and relaxation."],
        "space": ["<br>", "<br>"]
    },
    "item16": {
        "name": ["Item Name:", "Call of Duty Black Ops 2"],
        "brand": ["Item Brand:", "Activision"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$60.00"],
        "date": ["Pledge Date:", "10/20/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$10.00"],
        "motivation": ["Motivation:", "Need for entertainment and relaxation."],
        "space": ["<br>", "<br>"]
    },
    "item17": {
        "name": ["Item Name:", "Mini Refrigerator"],
        "brand": ["Item Brand:", "Black & Decker"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$120.00"],
        "date": ["Pledge Date:", "09/17/2012"],
        "priority": ["Priority:", "High!!!"],
        "timeFrame": ["Time Frame:", "0-6 months"],
        "amountSaved": ["Amount Saved:", "$50.00"],
        "motivation": ["Motivation:", "Buying it for my mom for Christmas."],
        "space": ["<br>", "<br>"]
    },
    "item18": {
        "name": ["Item Name:", "iPod"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$199.99"],
        "date": ["Pledge Date:", "10/28/2012"],
        "priority": ["Priority:", "Medium!!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$40.00"],
        "motivation": ["Motivation:", "Buying it for my moms birthday."],
        "space": ["<br>", "<br>"]
    },
    "item19": {
        "name": ["Item Name:", "Magic Mouse and Keyboard"],
        "brand": ["Item Brand:", "Apple"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$125.00"],
        "date": ["Pledge Date:", "10/21/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "Between 1-3 years"],
        "amountSaved": ["Amount Saved:", "$10.00"],
        "motivation": ["Motivation:", "Buy it when I get my Thunderbolt Display."],
        "space": ["<br>", "<br>"]
    },
    "item20": {
        "name": ["Item Name:", "Windows 8"],
        "brand": ["Item Brand:", "Microsoft"],
        "quantity": ["Quantity:", "1"],
        "cost": ["Total Cost:", "$99.99"],
        "date": ["Pledge Date:", "10/25/2012"],
        "priority": ["Priority:", "Low!"],
        "timeFrame": ["Time Frame:", "6 months to a year"],
        "amountSaved": ["Amount Saved:", "$30.00"],
        "motivation": ["Motivation:", "So I can dual boot on my Macbook."],
        "space": ["<br>", "<br>"]
    }
}